version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - '2181:2181' # OPEN ZOOKEEPER CLIENT PORT
      - '2888:2888' # OPEN ZOOKEEPER LEADER PORT
      - '3888:3888' # OPEN ZOOKEEPER LEADER PORT
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_QUORUM_LISTEN_ON_ALL_IPS: 'true'
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_PEER_PORT: 2888
      ZOOKEEPER_LEADER_PORT: 3888
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: "zookeeper:2888:3888"

  broker:
    image: confluentinc/cp-kafka:latest
    hostname: broker
    container_name: broker
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - '9092:9092' # OPEN INTERNAL PORT
      #- "29092:29092" # OPEN EXTERNAL PORT
      - '8080:8080' # OPEN PORT TO PROMETHEUS (MONITORING)
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092 # OPEN PORT 9092 TO INTERNAL CONNECTION, 29092 TO EXTERNAL
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://broker:9092" # OPEN PORT 9092 TO INTERNAL CONNECTION, 29092 TO EXTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT # INFORM THE CONNECTION PROTOCOL (SECURITY) FOR EACH LISTERNERS
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL # INFORM THE INTERNAL CONNECTION PORT
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_HEAP_OPTS: '-XX:MaxRAMPercentage=70.0'